events {
    worker_connections 4096;
}

http {
    # Tier 1: The Traffic Generator (Simulates Users)
    upstream generator_service {
        server generator:8080;
    }

    # Tier 2: The Rate Limit Workers (The Data Plane)
    upstream worker_cluster {
        server worker1:8080;
        server worker2:8080;
        server worker3:8080;
    }

    # Tier 3: The Management Node (The Control Plane)
    upstream manager_service {
        server manager:8080;
    }

    server {
        listen 80;

        # Add timeouts at LB level
        proxy_connect_timeout 5s;
        proxy_send_timeout 10s;
        proxy_read_timeout 10s;

        # 1. Route Load Test requests to the Generator
        location /api/benchmark/ {
            proxy_pass http://generator_service;
            proxy_set_header Host $host;
        }

        # 2. Route Rate Limit Checks to the Worker Cluster
        location /api/ratelimit/check {
            proxy_pass http://worker_cluster;
            proxy_next_upstream error timeout http_500 http_502 http_503 http_504;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            add_header X-Served-By-Worker $upstream_addr; 
        }

        # 3. Route Dashboard/Admin/Metrics to the Management Node
        location /admin/ {
            proxy_pass http://manager_service;
            proxy_set_header Host $host;
        }

        location /metrics {
            proxy_pass http://manager_service;
            proxy_set_header Host $host;
        }

        location /api/ratelimit/config {
            proxy_pass http://manager_service;
            proxy_set_header Host $host;
        }

        location /api/ratelimit/adaptive {
            proxy_pass http://manager_service;
            proxy_set_header Host $host;
        }

        location /actuator/ {
            proxy_pass http://manager_service;
            proxy_set_header Host $host;
        }
    }
}