server.port=8082
ratelimiter.redis.enabled=true
ratelimiter.security.api-keys.enabled=false
ratelimiter.loadbalancer.url=http://localhost:8081
spring.data.redis.host=localhost
spring.data.redis.port=6379
management.endpoint.health.show-details=always
management.endpoints.web.exposure.include=health,metrics
ratelimiter.adaptive.enabled=true
